name: Build Xcode project

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build Xcode project
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: mxcl/Xcodebuild
        uses: mxcl/xcodebuild@v3.4.0
        with:
          scheme: OpenCloudSDK
          action: build
          platform: iOS
          platform-version: 18.2
