name: "Pull translations from Transifex"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  pull-translations:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOYMENT_SSH_KEY }}
          ref: "main"

      - name: l10n-pull
        uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TX_TOKEN }}
          args: pull --force --skip --all

      - name: l10n-format
        shell: bash
        run: |
          beautifyJSON() {
            jq --sort-keys 'walk(if type == "object" then del(."th_TH", ."pt_PT", ."pt_BR", ."nn_NO", ."nb_NO", ."en_GB") else . end)' "$1" >"$1.tmp"
            mv "$1.tmp" "$1"
          }
          beautifyJSON "OpenCloudSDK/Resources/Localizable.xcstrings"
          beautifyJSON "OpenCloudUI/Resources/Localizable.xcstrings"         

      - name: Setup Swift
        uses: swift-actions/setup-swift@v2.1.0
            
      - name: Build ocstringstool
        run: |
         swift -v
         swiftc tools/ocstringstool/ocstringstool/main.swift -o /tmp/ocstringstool

      - name: Run ocstringstool
        run: /tmp/ocstringstool normalize "OpenCloudSDK/Resources" "OpenCloudUI/Resources"

      - uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          email: devops@opencloud.eu
          name: OpenClouders
          commit_message: "[tx] updated translations from transifex"
